const fs = require('fs');
const path = require('path');

const target = path.join(__dirname, 'routes', 'share.js');

const content = [
  "const express = require('express');",
  "const axios = require('axios');",
  "const User = require('../models/User');",
  "const Reminder = require('../models/Reminder');",
  "",
  "const router = express.Router();",
  "",
  "router.get('/:referralCode', async (req, res) => {",
  "  try {",
  "    const referralCode = req.params.referralCode;",
  "    const user = await User.findOne({ referralCode: referralCode.toUpperCase() });",
  "    if (!user) return res.status(404).send('<h1>Link not found</h1>');",
  "    const name = user.username;",
  "    const html = '<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\"><title>RemindMe</title><style>body{font-family:sans-serif;background:#f0f4f8;margin:0;display:flex;justify-content:center;align-items:center;min-height:100vh}.card{background:white;padding:30px;border-radius:12px;box-shadow:0 4px 15px rgba(0,0,0,.1);max-width:400px;width:90%}h2{color:#000080;text-align:center}.form-group{margin-bottom:15px}label{display:block;margin-bottom:5px;font-weight:bold}input,select{width:100%;padding:10px;border:1px solid #ccc;border-radius:6px;box-sizing:border-box}.btn{background:#4CAF50;color:white;border:none;padding:12px;width:100%;border-radius:6px;font-size:1.1rem;font-weight:bold;cursor:pointer}</style></head><body><div class=\"card\" id=\"formCard\"><h2>' + name + ' shares with you</h2><p style=\"text-align:center;color:#555\">Enter your birthday or wedding date</p><form id=\"reminderForm\"><div class=\"form-group\"><label>Your Name</label><input type=\"text\" id=\"name\" required></div><div class=\"form-group\"><label>Event Type</label><select id=\"type\"><option value=\"DOB\">Birthday</option><option value=\"Wedding\">Wedding Anniversary</option></select></div><div class=\"form-group\"><label>Relationship with ' + name + '</label><select id=\"relationship\"><option value=\"Friend\">Friend</option><option value=\"Relative\">Relative</option><option value=\"Colleague\">Colleague</option><option value=\"Other\">Other</option></select></div><div class=\"form-group\"><label>Your Phone Number (Optional)</label><input type=\"tel\" id=\"contactNumber\" placeholder=\"+91...\"></div><div class=\"form-group\"><label>Date</label><input type=\"date\" id=\"date\" required></div><button type=\"submit\" class=\"btn\">Submit</button></form></div><div class=\"card\" id=\"thankYouCard\" style=\"display:none;text-align:center\"><h2 style=\"color:#4CAF50\">Thank You!</h2><p>' + name + ' will never forget your special day! 🎉</p></div><script>document.getElementById(\"reminderForm\").addEventListener(\"submit\",async(e)=>{e.preventDefault();const p={personName:document.getElementById(\"name\").value,type:document.getElementById(\"type\").value,relationship:document.getElementById(\"relationship\").value,date:document.getElementById(\"date\").value,contactNumber:document.getElementById(\"contactNumber\").value};const r=await fetch(window.location.href,{method:\"POST\",headers:{\"Content-Type\":\"application/json\"},body:JSON.stringify(p)});if(r.ok){document.getElementById(\"formCard\").style.display=\"none\";document.getElementById(\"thankYouCard\").style.display=\"block\";}else{alert(\"Error!\");}});</script></body></html>';",
  "    res.send(html);",
  "  } catch (e) {",
  "    console.error('[SHARE GET]', e);",
  "    res.status(500).send('Server Error');",
  "  }",
  "});",
  "",
  "router.post('/:referralCode', async (req, res) => {",
  "  try {",
  "    const referralCode = req.params.referralCode;",
  "    const user = await User.findOne({ referralCode: referralCode.toUpperCase() });",
  "    if (!user) return res.status(404).json({ message: 'User not found' });",
  "    const { personName, type, relationship, date, contactNumber } = req.body;",
  "    const reminder = new Reminder({ userId: user._id, personName, type, relationship, date, contactNumber });",
  "    await reminder.save();",
  "    const BOT = process.env.TELEGRAM_BOT_TOKEN;",
  "    const CHAT = process.env.TELEGRAM_CHAT_ID;",
  "    if (BOT && CHAT) {",
  "      try {",
  "        const lines = [",
  "          'New Date Added via Shared Link!',",
  "          '',",
  "          'Link Owner: ' + user.username,",
  "          'Person Name: ' + personName,",
  "          'Event: ' + type,",
  "          'Relationship: ' + relationship,",
  "          'Date: ' + date,",
  "          'Contact: ' + (contactNumber || 'Not provided')",
  "        ];",
  "        await axios.post('https://api.telegram.org/bot' + BOT + '/sendMessage', { chat_id: CHAT, text: lines.join('\\n') });",
  "        console.log('[TELEGRAM] Notification sent');",
  "      } catch (err) {",
  "        console.error('[TELEGRAM] Error:', err.message);",
  "      }",
  "    }",
  "    res.status(201).json({ message: 'Success' });",
  "  } catch (e) {",
  "    console.error('[SHARE POST]', e);",
  "    res.status(500).json({ message: 'Error', error: e.message });",
  "  }",
  "});",
  "",
  "module.exports = router;"
].join('\n');

fs.writeFileSync(target, content, 'utf8');
console.log('share.js created! Size:', fs.statSync(target).size, 'bytes');
